import { getArray, getTheNameOfWeek, getToday } from "@/utils/main";
import Head from "next/head";
import { useState } from "react";
import {
  Paper,
  Stack,
  Typography,
  Container,
  Table,
  TableRow,
  TableCell,
  TableHead,
  TableBody,
} from "@mui/material";

export default function Home() {
  const [week, setWeek] = useState("");
  const [sanawjy, setSanawjy] = useState(getArray("s"));
  const [maydalawjy, setMaydalawjy] = useState(getArray("m"));

  return (
    <>
      <Head>
        <title>Time_Table_mut_b</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        maxWidth="lg"
        sx={{
          marginBottom: "100px",
          fontSize: {
            xs: "10px",
            sm: "12px",
            md: "16px",
          },
        }}
      >
        <Stack spacing={10} alignItems={"center"}>
          <Stack justifyContent={"center"} alignItems={"center"} spacing={1}>
            <Typography sx={{ fontSize: "2em" }}>Time-Table</Typography>{" "}
            <Typography sx={{ fontSize: "2em" }}>
              {getTheNameOfWeek() == "m" ? "Maydalawjy" : "Sanawjy"} hepde
            </Typography>
            <Typography sx={{ fontSize: "1.7em", color: "green" }}>
              Şu gün
            </Typography>
            <Typography sx={{ fontSize: "1.7em", color: "green" }}>
              {typeof getToday(new Date().getDay(), getTheNameOfWeek()) ===
              "string"
                ? getToday(new Date().getDay(), getTheNameOfWeek())
                : null}
            </Typography>
            <Typography sx={{ fontSize: "1.7em", color: "green" }}>
              {typeof getToday(new Date().getDay(), getTheNameOfWeek()) ===
              "object"
                ? getToday(new Date().getDay(), getTheNameOfWeek()).first_pair
                : null}
            </Typography>
            <Typography sx={{ fontSize: "1.7em", color: "green" }}>
              {typeof getToday(new Date().getDay(), getTheNameOfWeek()) ===
              "object"
                ? getToday(new Date().getDay(), getTheNameOfWeek()).second_pair
                : null}
            </Typography>
            <Typography sx={{ fontSize: "1.7em", color: "green" }}>
              {typeof getToday(new Date().getDay(), getTheNameOfWeek()) ===
              "object"
                ? getToday(new Date().getDay(), getTheNameOfWeek()).third_pair
                : null}
            </Typography>
          </Stack>
          <Paper elevation={8}>
            <Typography
              sx={{ textAlign: "center", marginTop: "20px", fontSize: "1.8em" }}
            >
              Sanawjy hepde
            </Typography>
            <Table sx={{ maxWidth: 650 }} aria-label="simple table">
              <TableHead>
                <TableRow>
                  <TableCell
                    sx={{
                      fontSize: "1.7em",
                      p: "0px",
                      pl: "5px",
                      pb: "10px",
                      pt: "10px",
                    }}
                  >
                    Gün
                  </TableCell>
                  <TableCell
                    sx={{ fontSize: "1.7em", p: "0px", pb: "10px", pt: "10px" }}
                    align="right"
                  >
                    1 para
                  </TableCell>
                  <TableCell
                    sx={{ fontSize: "1.7em", p: "0px", pb: "10px", pt: "10px" }}
                    align="right"
                  >
                    2 para
                  </TableCell>
                  <TableCell
                    sx={{ fontSize: "1.7em", p: "0px", pb: "10px", pt: "10px" }}
                    align="right"
                  >
                    3 para
                  </TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {sanawjy.map((item, index) => (
                  <TableRow
                    key={index}
                    sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
                  >
                    <TableCell
                      sx={{ fontSize: "1.2em", p: "0px", pl: "5px" }}
                      component="th"
                      scope="row"
                    >
                      {index + 1}
                    </TableCell>
                    <TableCell sx={{ fontSize: "1.2em" }} align="right">
                      {item.first_pair}
                    </TableCell>
                    <TableCell sx={{ fontSize: "1.2em" }} align="right">
                      {item.second_pair}
                    </TableCell>
                    <TableCell sx={{ fontSize: "1.2em" }} align="right">
                      {item.third_pair !== null && item.third_pair ? (
                        item.third_pair
                      ) : (
                        <span style={{ fontStyle: "italic", color: "red" }}>
                          boş
                        </span>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </Paper>
          <Paper elevation={8}>
            <Typography
              sx={{ textAlign: "center", marginTop: "20px", fontSize: "1.8em" }}
            >
              Maýdalawjy hepde
            </Typography>
            <Table sx={{ maxWidth: 650 }} aria-label="simple table">
              <TableHead>
                <TableRow>
                  <TableCell
                    sx={{
                      fontSize: "1.7em",
                      p: "0px",
                      pl: "5px",
                      pb: "10px",
                      pt: "10px",
                    }}
                  >
                    Gün
                  </TableCell>
                  <TableCell
                    sx={{ fontSize: "1.7em", p: "0px", pb: "10px", pt: "10px" }}
                    align="right"
                  >
                    1 para
                  </TableCell>
                  <TableCell
                    sx={{ fontSize: "1.7em", p: "0px", pb: "10px", pt: "10px" }}
                    align="right"
                  >
                    2 para
                  </TableCell>
                  <TableCell
                    sx={{ fontSize: "1.7em", p: "0px", pb: "10px", pt: "10px" }}
                    align="right"
                  >
                    3 para
                  </TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {maydalawjy.map((item, index) => (
                  <TableRow
                    key={index}
                    sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
                  >
                    <TableCell
                      sx={{ fontSize: "1.2em", p: "0px", pl: "5px" }}
                      component="th"
                      scope="row"
                    >
                      {index + 1}
                    </TableCell>
                    <TableCell sx={{ fontSize: "1.2em" }} align="right">
                      {item.first_pair}
                    </TableCell>
                    <TableCell sx={{ fontSize: "1.2em" }} align="right">
                      {item.second_pair}
                    </TableCell>
                    <TableCell sx={{ fontSize: "1.2em" }} align="right">
                      {item.third_pair !== null && item.third_pair ? (
                        item.third_pair
                      ) : (
                        <span style={{ fontStyle: "italic", color: "red" }}>
                          boş
                        </span>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </Paper>
        </Stack>
      </Container>
    </>
  );
}
